### ISSUE TITLE
AWS SSO: multiple credentials updates

### ISSUE THREAD

**Issue by iyesin** [andreabedini/aws-credentials-from-saml#2]
Hello,

I'm trying to setup some scripting for getting session creds for my aws-cli and stepped into some issue.
In case you have multiple roles to assume (see attachment), `credentials` file is updated at least twice. On first update typically there temporary session credentials (with lifetime limited to ~15 minutes). Second update gives you "long-term" credentials (limited either with aws or your org settings). Since file API for Firefox is optimized, it is very hard to catch second file update with something like inotify (at least for me, on Linux). Is there any way to get exact second set of creds?

UPD: I forgot main issue: if some process started right after first file update and before second (which could be seconds, because I need manually select role and click `Sign in`) it could stuck (like terraform does) or fail with message like `An error occurred (ExpiredToken) when calling the %any% operation: The provided token has expired.`

![multiple roles to assume](https://user-images.githubusercontent.com/13554666/80955288-52969a80-8dff-11ea-9cf8-4868420f6903.png)

**Comment by andreabedini** [comment]
Hi @iyesin, I am a bit confused. When you have multiple roles to assume, the intended behaviour is to assume all of them and download a single `credentials` file that has one profile per role. The profile name is computed from the role name but I see in your case the role name is repeated across accounts and maybe this is causing problems. At the moment I don't see how the extension is triggering multiple downloads.

**Comment by iyesin** [comment]
Hello @andreabedini,

role names a slightly different in their prefixes (masked part).
Plugin creates one file but updates it at least twice. Can you give me a hint how I can give a trace (or some other sort of debug output) showing what's going on with plugin? Say, some debug output from `onBeforeRequest` or `downloadAs` functions with call context.

**Comment by iyesin** [comment]
This issue was a mess of wrong assumptions and wrong wording of mine.
Closing.
