### ISSUE TITLE
Doesn't work for China regions

### ISSUE THREAD

**Issue by reznid01** [andreabedini/aws-credentials-from-saml#8]
Doesn't work for China regions. Is there any work-around to make it working for CN?

**Comment by andreabedini** [comment]
hi @reznid01, be aware I am not using this anymore, also I have no experience with China regions.

I see the AWS Java SDK has this note

>  The default AWS Security Token Service (STS) endpoint ("sts.amazonaws.com") works for all accounts that are not for China (Beijing) region or GovCloud. You only need to change the endpoint to "sts.cn-north-1.amazonaws.com.cn" when you are requesting session credentials for services in China(Beijing) region or "sts.us-gov-west-1.amazonaws.com" for GovCloud. 

The code currently hardcodes `sts.amazonaws.com` in https://github.com/andreabedini/aws-credentials-from-saml/blob/25ec9f9aa0ccdc25abbe1a9341467d6df5cdf814/background.js#L35, perhaps one could try to change that to `sts.cn-north-1.amazonaws.com.cn`.

Let me know if it works,
Andrea
